use_move_base_urdf_viz_web_client = false
use_navigation_urdf_viz_web_client = false

[[ros_clients_configs]]
name = "arm"
joint_names = ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6"]
controller_name = "/xarm/xarm6_traj_controller"
complete_allowable_errors = [0.02, 0.02, 0.02, 0.02, 0.02, 0.02]


[openrr_clients_config]
urdf_path = "../../xarm_ros/xarm_description/urdf/xarm6_robot.urdf.xacro"
self_collision_check_pairs = ["joint1:joint3"]

[[openrr_clients_config.collision_check_clients_configs]]
name = "arm_collision_checked"
client_name = "arm"

[[openrr_clients_config.ik_clients_configs]]
name = "arm_ik"
client_name = "arm_collision_checked"
solver_name = "arm_ik_solver"

[openrr_clients_config.ik_solvers_configs.arm_ik_solver]
ik_target = "joint_eef"

[[openrr_clients_config.joints_poses]]
pose_name = "zero"
client_name = "arm_collision_checked"
positions = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

[[openrr_clients_config.joints_poses]]
pose_name = "ready"
client_name = "arm_collision_checked"
positions = [0.0, -0.7, 1.4, -0.7, 1.57, -3.14]
